export const architectsData = [
  {
    imageSrc: '/images/architects/architect01.jpg',
    name: 'Willy Smith',
    role: 'Architect',
    skills: ['Architecture', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect02.jpg',
    name: 'John Carter',
    role: 'Architect',
    skills: ['Building', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect03.jpg',
    name: 'Lisa Bennett',
    role: 'Architect',
    skills: ['Architecture', 'SketchUp'],
  },
  {
    imageSrc: '/images/architects/architect04.jpg',
    name: 'Ethan Roberts',
    role: 'Architect',
    skills: ['Engineering', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect05.jpg',
    name: 'Michael Thompson',
    role: 'Architect',
    skills: ['Interior', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect06.jpg',
    name: 'Sandra Harrison',
    role: 'Architect',
    skills: ['Landscape', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect07.jpg',
    name: 'Alex Wright',
    role: 'Architect',
    skills: ['Management', 'SketchUp'],
  },
  {
    imageSrc: '/images/architects/architect08.jpg',
    name: 'Henrieta Evans',
    role: 'Architect',
    skills: ['Coordination', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect09.jpg',
    name: 'Christopher Scott',
    role: 'Architect',
    skills: ['Construction', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect10.jpg',
    name: 'Daniel Hughes',
    role: 'Architect',
    skills: ['Design', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect11.jpg',
    name: 'Emma Clark',
    role: 'Architect',
    skills: ['Urban Design', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect12.jpg',
    name: 'Oliver Brooks',
    role: 'Architect',
    skills: ['Sustainable Design', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect13.jpg',
    name: 'Sophia Lewis',
    role: 'Architect',
    skills: ['Interior Design', 'SketchUp'],
  },
  {
    imageSrc: '/images/architects/architect14.jpg',
    name: 'Nora Baker',
    role: 'Architect',
    skills: ['Project Management', 'AutoCAD'],
  },
  {
    imageSrc: '/images/architects/architect15.jpg',
    name: 'Isabella King',
    role: 'Architect',
    skills: ['Landscape Architecture', 'Revit'],
  },
  {
    imageSrc: '/images/architects/architect16.jpg',
    name: 'Lucas Moore',
    role: 'Architect',
    skills: ['Architecture', 'SketchUp'],
  },
  {
    imageSrc: '/images/architects/architect17.jpg',
    name: 'James Anderson',
    role: 'Architect',
    skills: ['Residential Design', 'AutoCAD'],
  },
];
